[package]
name = "fmt_import"
version = "0.1.0"
authors = ["C.Solovev <constantine.solovev@gmail.com>"]
edition = "2021"

[dependencies]

structopt = "0.3"
ignore = "0.4"
toml = "0.5"
serde = "1"
serde_derive = "1"
eyre = "0.6"
itertools = "0.10"
ahash = "0.8"


